### ISSUE TITLE
on the scoring engine, Its still saying on the terminal that the firewall gave 5 points instead of 7, its not a big deal, just in the echo.

### ISSUE THREAD

**Issue by AlejandroDamas** [Martin104921/Scripts#1]

**Comment by Simondickerman** [comment]
Thanks man, I'll fix it. Good find!

**Comment by AlejandroDamas** [comment]
no problem I just didn't know how to get the script in order to edit it, so I just posted a comment.

**Comment by Simondickerman** [comment]
You can edit the code in guthub, just click the button that looks like a pencil.

**Comment by AlejandroDamas** [comment]
okay
